### ISSUE TITLE
Improvements to Records Analysis

### ISSUE THREAD

**Issue by Jambrose777** [SAuroux/wca-analysis#1]
[Results-Record-Markers-Analysis]

All of these are based off the normal calculations for having a computed value.

Pre-2013-01-01:
- [x] Anything that happens at only 1 competition is not any type of error.
- [x] Anything that happens during the same time frame at multiple competitions is a potential error.

Post-2013-01-01:
- [x] Any Competition / Record Type that is 1 day and has multiple records is a Definite error.
- [x] Any Competition that spans over multiple days and has multiple records  is a potential error.
- [x] Any Competition which has # of days < # of records set at competition is a Definite error.
- [x] Ties should always be marked as awarded records. (otherwise definite error).

Bugs:
- [x] If Competition A happens on day 1, Competition B happens on day 2, and Competition C happens on both days. If A and B have a similar record type, they show as a conflict, though they are on different days.

**Comment by SAuroux** [comment]
@Jambrose777 Sorry for taking a "little" while but I am confident now that I addressed all of the points above in https://github.com/SAuroux/wca-analysis/commit/e392284928fd79d784ab274c757829e12749d93c.
